### ISSUE TITLE
requests.exceptions.ConnectionError

### ISSUE THREAD

**Issue by kynikos** [lahwaacz/wiki-scripts#29]
Nothing major, rerunning the script worked just fine, but maybe you want to catch this exception (or forward this upstream?) :)
All system and dependency libraries up to date.

```
$ python statistics.py -s
INFO     Starting new HTTPS connection (1): wiki.archlinux.org
INFO     Loading data from /home/dario/.cache/wiki-scripts/wiki.archlinux.org/AllRevisionsProps.db.json.gz ...
WARNING  API warning(s) for query {'action': 'query', 'list': 'recentchanges', 'rclimit': '1', 'rcprop': 'ids', 'rctype': 'edit'}:
* Formatting of continuation data will be changing soon. To continue using the current formatting, use the 'rawcontinue' parameter. To begin using the new format, pass an empty string for 'continue' in the initial query.
INFO     Fetching revids 407566-407833
INFO     Saving data to /home/dario/.cache/wiki-scripts/wiki.archlinux.org/AllRevisionsProps.db.json.gz ...
Traceback (most recent call last):
  File "/mnt/archive/Development/wiki-scripts/requests/packages/urllib3/connectionpool.py", line 376, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/archive/Development/wiki-scripts/requests/packages/urllib3/connectionpool.py", line 559, in urlopen
    body=body, headers=headers)
  File "/mnt/archive/Development/wiki-scripts/requests/packages/urllib3/connectionpool.py", line 378, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1174, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 282, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 251, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/archive/Development/wiki-scripts/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/mnt/archive/Development/wiki-scripts/requests/packages/urllib3/connectionpool.py", line 609, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/mnt/archive/Development/wiki-scripts/requests/packages/urllib3/util/retry.py", line 245, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/mnt/archive/Development/wiki-scripts/requests/packages/urllib3/packages/six.py", line 309, in reraise
    raise value.with_traceback(tb)
  File "/mnt/archive/Development/wiki-scripts/requests/packages/urllib3/connectionpool.py", line 559, in urlopen
    body=body, headers=headers)
  File "/mnt/archive/Development/wiki-scripts/requests/packages/urllib3/connectionpool.py", line 378, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1174, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 282, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 251, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "statistics.py", line 321, in <module>
    sys.exit(statistics.run())
  File "statistics.py", line 110, in run
    self._compose_page()
  File "statistics.py", line 134, in _compose_page
    self.cliargs.us_minrecedits, self.cliargs.us_rcerrhours)
  File "statistics.py", line 242, in __init__
    self.modules = UserStatsModules(self.db_allrevsprops, round_to_midnight=True)
  File "/mnt/archive/Development/wiki-scripts/statistics_modules.py", line 41, in __init__
    wrapped_input = [map(sortkey, _inner_generator(self.db["revisions"])), map(sortkey, _inner_generator(self.db["deletedrevisions"]))]
  File "/mnt/archive/Development/wiki-scripts/ws/cache/__init__.py", line 182, in __getitem__
    self._load_and_update(key)
  File "/mnt/archive/Development/wiki-scripts/ws/cache/__init__.py", line 179, in _load_and_update
    self.update(key)
  File "/mnt/archive/Development/wiki-scripts/ws/cache/AllRevisionsProps.py", line 55, in update
    lastrevid = self._get_last_revid_api()
  File "/mnt/archive/Development/wiki-scripts/ws/cache/AllRevisionsProps.py", line 82, in _get_last_revid_api
    result = self.api.call_api(action="query", list="recentchanges", rcprop="ids", rctype="edit", rclimit="1")
  File "/mnt/archive/Development/wiki-scripts/ws/core/connection.py", line 187, in call_api
    result = self.request("GET", self.api_url, params=params)
  File "/mnt/archive/Development/wiki-scripts/ws/core/rate.py", line 61, in rate_limit_func
    ret = func(*args, **kargs)
  File "/mnt/archive/Development/wiki-scripts/ws/core/connection.py", line 144, in request
    response = self.session.request(method, url, **kwargs)
  File "/mnt/archive/Development/wiki-scripts/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/mnt/archive/Development/wiki-scripts/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/mnt/archive/Development/wiki-scripts/requests/adapters.py", line 420, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
```

**Comment by lahwaacz** [comment]
If rerunning the script worked fine, I have no idea how the "unexpected keyword argument" error might occur only once...
Anyway, the `ws` lib's problem should be fixed in 3307fe1154a473180d55ccf171992f80ad90d0aa, leaving it up to the scripts to catch it too. Maybe there should be an option to automatically retry all broken connections?

**Comment by kynikos** [comment]
I have no idea either why that happened, I just hoped you did :P
I don't have the time to go through the code now, but if the exception can be raised also during long processes, it would probably be wise to catch it and retry it at least automatically, or prompting the user. In Wiki Monkey I'm doing something like that directly in the generic querying function, so plugins don't have to worry about it; in the case of wiki-scripts I can't tell whether this could have bad side effects though...

**Comment by lahwaacz** [comment]
The `TypeError: getresponse() got an unexpected keyword argument 'buffering'` exception seems to happen also with timeouts, see https://github.com/shazow/urllib3/issues/656#issuecomment-115484197

**Comment by lahwaacz** [comment]
I think that this is simply how requests/urllib3 works and on the wiki-scripts side this should be solved by https://github.com/lahwaacz/wiki-scripts/commit/bc5efa7d, https://github.com/lahwaacz/wiki-scripts/commit/5de3216d and https://github.com/lahwaacz/wiki-scripts/commit/f6ecef34, so closing.
