### ISSUE TITLE
toc.py - TypeError: all arguments must be str, not: datetime.datetime

### ISSUE THREAD

**Issue by kynikos** [lahwaacz/wiki-scripts#45]
Hi, I wish I could help more, I get this when running `toc.py -s` in 47dbd74bbd62947d1bdaf42a0cc3dbe819eb42a6, my `python` is at 3.6.2-1, cheers:

```                    
INFO     Fixing language of categories on page [[Chromium (Español)]]...
Traceback (most recent call last):
  File "toc.py", line 363, in <module>
    toc.run()
  File "toc.py", line 291, in run
    cat.fix_allpages()
  File "/home/dario/dev/arch/wiki-scripts/ws/interlanguage/Categorization.py", line 87, in fix_allpages
    edit_interactive(self.api, page["title"], page["pageid"], text_old, text_new, timestamp, self.edit_summary, bot="")
  File "/home/dario/dev/arch/wiki-scripts/ws/interactive.py", line 96, in edit_interactive
    diff = diff_highlighted(text_old, text_new, title + ".old", title + ".new", basetimestamp, "<utcnow>")
  File "/home/dario/dev/arch/wiki-scripts/ws/diff.py", line 62, in diff_highlighted
    text = "\n".join(diff)
  File "/usr/lib/python3.6/difflib.py", line 1177, in unified_diff
    _check_types(a, b, fromfile, tofile, fromfiledate, tofiledate, lineterm)
  File "/usr/lib/python3.6/difflib.py", line 1312, in _check_types
    raise TypeError('all arguments must be str, not: %r' % (arg,))
TypeError: all arguments must be str, not: datetime.datetime(2017, 9, 9, 0, 47, 10)
```

**Comment by lahwaacz** [comment]
Hmm, bug in an untested code path... I use [WikEdDiff](https://aur.archlinux.org/packages/python-wikeddiff-git/) instead of difflib, so I couldn't notice.
