### ISSUE TITLE
toc.py:  IndexError: list index out of range

### ISSUE THREAD

**Issue by kynikos** [lahwaacz/wiki-scripts#86]
On 41e05d50136bb4a49bd4b4144470293ca278dc17:

```
$ python toc.py -s

...

Traceback (most recent call last):
  File "/home/dario/dev/arch/wiki-scripts/toc.py", line 363, in <module>
    toc.run()
  File "/home/dario/dev/arch/wiki-scripts/toc.py", line 291, in run
    cat.fix_allpages()
  File "/home/dario/dev/arch/wiki-scripts/ws/interlanguage/Categorization.py", line 81, in fix_allpages
    timestamp = page["revisions"][0]["timestamp"]
IndexError: list index out of range
```

Have a great day mate!!! ^^

**Comment by lahwaacz** [comment]
Sorry for the delay! I think it should be fixed in https://github.com/lahwaacz/wiki-scripts/commit/e48f57972516e812fb6d3375ca9da61b7db7ad0e, please let me know if it works.

**Comment by kynikos** [comment]
It worked! I've been watching all the work that you're doing for the wiki, you're amazing, thank you!! :D
